name: PyPI Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for hatch-vcs
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Set up Python
        run: uv python install 3.10
      
      - name: Install dependencies
        run: uv sync --all-extras
      
      - name: Display version info
        run: |
          echo "Building from ref: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          uv run python -c "import hatchling.metadata.core; print(f'Version: {hatchling.metadata.core.ProjectMetadata.from_file(\"pyproject.toml\").version}')" || echo "Version determined by hatch-vcs"
      
      - name: Run tests
        run: uv run pytest tests/ -v --tb=short
      
      - name: Run linting
        run: uv run ruff check .
      
      - name: Build package
        run: uv build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
