name: PyPI Release

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          uv sync
      
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Create version tag
        run: |
          # Get base version and increment based on commits since last tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.3")
          LAST_VERSION=$(echo $LAST_TAG | sed 's/^v//')
          COMMITS_SINCE=$(git rev-list ${LAST_TAG}..HEAD --count 2>/dev/null || echo "1")
          
          if [ "$COMMITS_SINCE" -eq "0" ]; then
            echo "No new commits since $LAST_TAG, skipping tag creation"
            exit 0
          fi
          
          MAJOR=$(echo $LAST_VERSION | cut -d. -f1)
          MINOR=$(echo $LAST_VERSION | cut -d. -f2)
          PATCH=$(echo $LAST_VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          TAG="v$NEW_VERSION"
          
          # Check if tag already exists
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping tag creation"
          else
            git tag $TAG
            git push origin $TAG
            echo "Created tag: $TAG (version: $NEW_VERSION)"
          fi
      
      - name: Run tests
        run: |
          uv run pytest tests/ -v
      
      - name: Run linting
        run: |
          uv run ruff check .
      
      - name: Build package
        run: |
          uv build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
