name: PyPI Release

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          uv sync
      
      - name: Create version tag
        run: |
          TAG="v$(date +%Y%m%d.%H%M%S)"
          git tag $TAG
          git push origin $TAG
          echo "Created tag: $TAG"
      
      - name: Run tests
        run: |
          uv run pytest tests/ -v
        continue-on-error: true
      
      - name: Run linting
        run: |
          uv run ruff check .
        continue-on-error: true
      
      - name: Build package
        run: |
          uv build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
