name: Test PyPI Release

on:
  push:
    branches: [ "**" ]  # All branches
  pull_request:
    branches: [ "**" ]  # All pull requests
  workflow_dispatch:    # Manual trigger

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for hatch-vcs
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Set up Python
        run: uv python install 3.10
      
      - name: Install dependencies
        run: uv sync --all-extras
      
      - name: Run linting
        run: uv run ruff check .
        continue-on-error: true
      
      - name: Run tests
        run: uv run pytest tests/ -v --tb=short
        continue-on-error: true
      
      - name: Build package
        run: uv build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
      
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name != 'pull_request'  # Skip publishing for PRs
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          print-hash: true
          skip-existing: true
